# Generated by Django 3.1.7 on 2021-04-02 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'parent'), (2, 'teacher'), (3, 'secretary'), (4, 'headteacher'), (5, 'admin')], null=True),
        ),
    ]
