# Generated by Django 3.1.7 on 2021-03-29 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Exams',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('names', models.CharField(blank=True, max_length=200, null=True)),
                ('date_of_birth', models.IntegerField(blank=True, null=True)),
                ('adm_no', models.CharField(blank=True, max_length=20, null=True)),
                ('residence', models.CharField(blank=True, max_length=200, null=True)),
                ('gender', models.CharField(blank=True, max_length=50, null=True)),
                ('stream', models.CharField(blank=True, max_length=250, null=True)),
                ('clas', models.CharField(blank=True, max_length=250, null=True)),
            ],
        ),
    ]
